### ISSUE TITLE
License

### ISSUE THREAD

**Issue by waynegraham** [endangereddataweek/endangereddataweek.org#1]
I noticed that the license for the project is CC-BY, which is typically for content and not applied to the code in a repository. Source code licensing gets weird quickly, but it would be a good thing to change the license for the source code to something like [MIT](https://opensource.org/licenses/MIT) or some other permissive open source license, but keep the content on the site CC-BY.

Does anyone have thoughts on this?

**Comment by hepplerj** [comment]
I think it's a good idea to add an MIT license to the code, and stick with CC-BY for content.
