### ISSUE TITLE
timezones

### ISSUE THREAD

**Issue by nowviskie** [endangereddataweek/endangereddataweek.org#10]
We don't need to do anything fancy, and I added the phrase "local time" to the events pages themselves, to help with this, but it might be less than obvious to people browsing virtual/online events what timezone they're in. This relates to #9, and I think implies that we should add some help text to the form so that everybody's encouraged to add a real location rather than try typing "virtual" or "everywhere" in the location field like I did.

**Comment by brandontlocke** [comment]
I added help text to both 'Institution' and 'Location' as those were confusing anyway. I also added you to the folder, so feel free to futher clarify.
