### ISSUE TITLE
create email alias and add to footer text as "Contact."

### ISSUE THREAD

**Issue by nowviskie** [endangereddataweek/endangereddataweek.org#11]
endangereddata@diglib.org alias, if possible to add Brandon & Jason alongside Wayne, Bethany, Katherine, Becca -- otherwise a new Google group?

**Comment by nowviskie** [comment]
Since we may not get to this in time for launch, I added a link to info@diglib. Can change later.

**Comment by waynegraham** [comment]
I can't make distro lists in the AD with external addresses, but have a ticket in to create it with the addresses. Should be ready later this morning...
