### ISSUE TITLE
something up with geoparser?

### ISSUE THREAD

**Issue by nowviskie** [endangereddataweek/endangereddataweek.org#14]
Not sure why the two new NCSU events aren't showing up on the map. Location field is specified with street address and zip code, and I tried altering the Institution field in case "NCSU Libraries" just didn't parse, but no dice. I was going to add lat/long manually, but decided to leave it blank for debugging.

Here's one: http://endangereddataweek.org/events/2017-04-20-data-rescue-101-what-why-and-how/

**Comment by waynegraham** [comment]
For whatever reason the location isn't getting a result back from the Google geocoding API; also checked it manually in the US Census geocoded (https://geocoding.geo.census.gov/geocoder/geographies/onelineaddress?address=+Broughton+Dr%2C+Raleigh%2C+NC+27695&benchmark=4&vintage=4). Maybe this is a "new" road? I'll look in to it more...

**Comment by waynegraham** [comment]
None of the geocodes I tried actually matched this, so I search for Hill library and got it's coordinates and added them manually. This fixes it for the interim, but let's keep an eye on this to see if it pops up again, or was just a fluke in the way it was trying to parse that string.

**Comment by nowviskie** [comment]
Thanks! I guess I thought it'd default to the zip code if it couldn't actually find the street, but I guess precision>ambiguity in web-mapping.
