### ISSUE TITLE
formatting issue

### ISSUE THREAD

**Issue by nowviskie** [endangereddataweek/endangereddataweek.org#16]
on a new event: http://endangereddataweek.org/events/2017-04-21-data-awareness-day/

`Error: could not read file /Users/nowviskie/Projects/endangereddataweek.org/_events/2017-04-21-data-awareness-day.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1`

**Comment by waynegraham** [comment]
There are extra quotes in the excerpt which is causing the issue. I'll find a way to fix this...
