### ISSUE TITLE
Web Analytics

### ISSUE THREAD

**Issue by waynegraham** [endangereddataweek/endangereddataweek.org#2]
Is there any desire for any web analytics for this project? Currently there is nothing set up...

**Comment by hepplerj** [comment]
It might be another way to measure interest (besides number of events and attendees at those events). Does DLF have a way they want to track that? Or, would we just set up something like Google Analytics under one of our own accounts?

**Comment by waynegraham** [comment]
We just use Google Analytics, nothing too fancy. If you want to set it up, I've got a snip for tracking beacons...

**Comment by hepplerj** [comment]
Great, I'll do that today. You just need the tracking ID?

**Comment by waynegraham** [comment]
Yeah, just add it to https://github.com/endangereddataweek/endangereddataweek.org/blob/gh-pages/_config.yml#L10

**Comment by hepplerj** [comment]
Done.

**Comment by waynegraham** [comment]
closed in 48d4ec68c2708a2e2d05bf10436304ab52e1d466
