### ISSUE TITLE
File cleanup

### ISSUE THREAD

**Issue by waynegraham** [endangereddataweek/endangereddataweek.org#21]
We have some house keeping that would be good to do. Does anyone have comments on the following?

# Needs Updating

- [humans.txt](https://github.com/endangereddataweek/endangereddataweek.org/blob/gh-pages/humans.txt): We're probably missing people and/or orgs to thank.

# Candidates for Removal

- [LICENSE.md](https://github.com/endangereddataweek/endangereddataweek.org/blob/gh-pages/LICENSE.md). The license file in these projects is typically for the source code, and this is a CC license which is typically for content (the notice is on the pages). We also have [LICENSE](https://github.com/endangereddataweek/endangereddataweek.org/blob/gh-pages/LICENSE), an MIT license for the source code.
- [edwrake.txt](https://github.com/endangereddataweek/endangereddataweek.org/blob/gh-pages/edwrake.txt): This looks like a terminal redirect of `rake` output
- [Makefile](https://github.com/endangereddataweek/endangereddataweek.org/blob/gh-pages/Makefile) - folks should be using `gulp` instead now for local development (it includes a lot of automation for building different components of the content, including processing assets)

**Comment by hepplerj** [comment]
On candidates for removal: I don't see any reasons why we should keep what you've listed here, @waynegraham.  

On updating: I'll add a couple things to humans.txt, but I'm likely overlooking things.
