### ISSUE TITLE
Page rendering problem with punctuation in titles

### ISSUE THREAD

**Issue by hepplerj** [endangereddataweek/endangereddataweek.org#8]
I just added an event with a question mark in the title, which was pulled into the URL for the event page. But it's getting 404'ed:

http://endangereddataweek.org/events/2017-04-17-what-is-endangered-data?/

**Comment by nowviskie** [comment]
I just noticed this (before seeing your ticket) and manually took the ? out of the filename, for a temporary fix. Of course it'll break again when it's regenerated. Flagging for @waynegraham to take a look when he has the chance...
