### ISSUE TITLE
table and map break if location can't be geo-parsed

### ISSUE THREAD

**Issue by nowviskie** [endangereddataweek/endangereddataweek.org#9]
I used the web form to enter an event with location "virtual" and managed to break everything to hell. It seems if lat/long is missing for one event, neither the table list nor any map events will render. 

I hand-edited files for a temporary fix, setting the location to the home base for the webinar, but this may break again if new events are added before the spreadsheet is updated (I don't have access to that -- this was the NDSA event), and surely people will try to put some other un-locatable stuff in. 

We should also put some indication in the web form of how virtual/online events should be handled!

**Comment by nowviskie** [comment]
(Sorry, guys! But I guess it's better I break it now than Monday.)

**Comment by nowviskie** [comment]
You are both insanely fast and amazing. Thanks!

**Comment by nowviskie** [comment]
Could still use @brandontlocke's fixing the spreadsheet for this one event (or just give me access and I'll do it), so that the NDSA one doesn't get overwritten and disappear from the map. (This would be bad because of timezone issues, #10.)

**Comment by nowviskie** [comment]
revised spreadsheet and Brandon added help text, fixing #10, so all done!

**Comment by brandontlocke** [comment]
Would it make sense for us to add a field for 'is virtual' and either link to a page with virtual events or highlight them on the list in some way? It looks like there will be at least 3 of them...

**Comment by nowviskie** [comment]
I'd be reluctant to create a different page for that, and it may be interesting for folks to see the "home base" of various virtual events -- plus we would still have the time zone issue (3pm for whom?) -- so what about indicating virtual events with a symbol or something in the table, for now?

**Comment by waynegraham** [comment]
We can have the field for the time include the timezone (e.g. 2:00 EST), it's just a string field. The reason the table didn't display was that there was a parsing error on the JSON object when a location couldn't be found (fixed in eaf08d1). These events can now have a location of ("online"); they won't be on the map, but will be on the list of events. 

Does this work for this issue? I can also find some symbology to mark this as online too...

**Comment by nowviskie** [comment]
My only hesitation is losing all 3 (Rachel's is coming soon) "east coast-based" virtual events from a sparse map right before launch. Even though, logically, it makes more sense for them not to be there, rhetorically it helps. I really like the idea of having a check box on the form and an indicator in the table for these, though. Could we just do that, for now, and then make another update to remove them from the map once it gets more crowded?
